name: Test python package dpath-python with regexp extension
  # ------------------------------------------------------------
  # (C) Alain Lichnewsky, 2021, 2022, 2023
  #
  # For running under Github's Actions
  #
    # ------------------------------------------------------------
  
  # *****************************
  # ADDED FOR TESTING PRIOR TO PR
  # REMOVE FROM PR submission
  # *****************************

on:
    workflow_dispatch:
    # Allows manual dispatch from the Actions tab

jobs:
    test-python3:

        timeout-minutes: 60

        runs-on: ubuntu-latest

        strategy:
            matrix:
                # Match versions specified in tox.ini and tox-set-rex.ini
                python-version: ['3.8', '3.11', 'pypy3.7', 'pypy3.9']

        steps:
            - name: Checkout code
              uses: actions/checkout@main

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@main
              with:
                  python-version: ${{ matrix.python-version }}
                  architecture: 'x64'

            - name: Ascertain configuration
              #
              #    Collect information concerning $HOME and the location of
              #    file(s) loaded from Github/
              run: |
                echo Working dir: $(pwd)
                echo Files at this location:
                ls -ltha
                echo HOME: ${HOME}
                echo LANG: ${LANG}  SHELL: ${SHELL}
                which python
                echo LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}
                echo PYTHONPATH: \'${PYTHONPATH}\'

            - name: Install dependencies
              shell: bash
              if: always()
              #  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
              #  requirements install the test framework, which is not
              #  required by the package in setup.py
              #  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
              run: |
                python -m pip install --upgrade pip setuptools wheel \
                        nose2 hypothesis
                if [ -f requirements.txt ]; then
                   pip install -r requirements.txt;
                fi
                python setup.py install
                pip install tox
                echo "Installed tox"

            - name: Tox test with default  DPATH_ACCEPT_RE_REGEXP_IN_STRING = FALSE
              shell: bash
              if: always()
              #  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
              #  tox testing, here tox.ini is used
              #  DPATH_ACCEPT_RE_REGEXP_IN_STRING = FALSE (default)
              #  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
              run: |
                tox
                echo "Ran tox"

            - name: Tox test with DPATH_ACCEPT_RE_REGEXP_IN_STRING = TRUE
              shell: bash
              if: always()
              #  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
              #  tox testing,  here tox-set-rex.ini is used
              #  DPATH_ACCEPT_RE_REGEXP_IN_STRING = TRUE
              #  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
              run: |
                tox -c tox-set-rex.ini
                echo "Ran tox -c tox-set-rex.ini"
               